### ISSUE TITLE
Cannot create protobuf/protobuf_bundle.json: Directory nonexistent npm ERR! code ELIFECYCLE npm ERR! errno 2

### ISSUE THREAD

**Issue by VishalDalve** [askmish/sawtooth-simplewallet#23]
Things I have done :

Installed latest Node(8.11.3)& npm version.
Started JavaScript essential thing using docker-compose up (used javascript .yaml file).

Things giving error:

Want to setup Javascript transaction processor so moved to dir jsprocessor.

Trying to install all node modules using `$ npm install`, but giving error shown in image. I think it is relate to node js.

Reinstalled Node & NPM, Externally installed npm module that producing error but no effect.

What am I doing wrong?
![nder](https://user-images.githubusercontent.com/19385747/41638008-8d57ad72-7474-11e8-8085-631f7a8c9895.png)

**Comment by VishalDalve** [comment]
Hi, anyone able to start "jsprocessor" TP successfully? on Ubuntu 16.04?

**Comment by askmish** [comment]
@VishalDalve Fixed. Please refer: https://github.com/askmish/sawtooth-simplewallet/pull/26
