### ISSUE TITLE
simplewallet-processor container exists without any error

### ISSUE THREAD

**Issue by rohitkhatri** [askmish/sawtooth-simplewallet#24]
simplewallet-processor container exists without any error

here's the log of docker container:

	-- The CXX compiler identification is GNU 5.4.0
	-- Check for working CXX compiler: /usr/bin/c++
	-- Check for working CXX compiler: /usr/bin/c++ -- works
	-- Detecting CXX compiler ABI info
	-- Detecting CXX compiler ABI info - done
	-- Detecting CXX compile features
	-- Detecting CXX compile features - done
	-- Looking for C++ include pthread.h
	-- Looking for C++ include pthread.h - found
	-- Looking for pthread_create
	-- Looking for pthread_create - not found
	-- Looking for pthread_create in pthreads
	-- Looking for pthread_create in pthreads - not found
	-- Looking for pthread_create in pthread
	-- Looking for pthread_create in pthread - found
	-- Found Threads: TRUE  
	-- Configuring done
	-- Generating done
	-- Build files have been written to: /project/simplewallet/cxxprocessor/build
	Scanning dependencies of target simplewallet-tp
	[ 50%] Building CXX object CMakeFiles/simplewallet-tp.dir/simplewallet-tp.cpp.o
	[100%] Linking CXX executable bin/simplewallet-tp
	[100%] Built target simplewallet-tp
	-- Configuring done
	-- Generating done
	-- Build files have been written to: /project/simplewallet/cxxprocessor/build
	[100%] Built target simplewallet-tp

**Comment by askmish** [comment]
Fixed. Please refer: https://github.com/askmish/sawtooth-simplewallet/pull/25
