### ISSUE TITLE
Javascript processor not working when using native installation

### ISSUE THREAD

**Issue by yashvadhvani** [askmish/sawtooth-simplewallet#35]
I am using native installation and trying to perform deposit but the balance is showing as undefined.

**Comment by askmish** [comment]
@yashvadhvani Could you provide more details about your setup and how to reproduce the issue?

**Comment by yashvadhvani** [comment]
Current working directory is: /home/yash/Desktop/jsclient
Storing at: 7e266499bec1960a5b05d0173bcf49673ba1505a17038afa2dfb58a73074a178071bae
Getting from: http://127.0.0.1:8008/state/7e266499bec1960a5b05d0173bcf49673ba1505a17038afa2dfb58a73074a178071bae
Promise { <pending> }
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
    at Function.from (buffer.js:208:11)
    at new Buffer (buffer.js:183:17)
    at fetch.then.then (/home/yash/Desktop/jsclient/routes/SimpleWalletClient.js:139:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1064) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by yashvadhvani** [comment]
facing the above issue

**Comment by yashvadhvani** [comment]
I am using jsprocessor

**Comment by yashvadhvani** [comment]
var geturl = 'http://127.0.0.1:8008/state/' + this.address
not able to find the state using geturl as it is giving me a 404

**Comment by askmish** [comment]
@yashvadhvani I'm looking into this, but I'm into poet2.0 work so a fix may get a bit delayed.
