### ISSUE TITLE
Login not working on js client UI

### ISSUE THREAD

**Issue by shonjs** [askmish/sawtooth-simplewallet#36]
When clicking the login button after giving the username, in the js client UI, it doesn't go to the home page.
Refreshes and stays on the same page.
(Browser - firefox 63.0.3)

**Comment by shonjs** [comment]
The issue seems to be with the default button click behavior. The control returns before the response.
Seems to work with a preventDefault.

**Comment by askmish** [comment]
Thanks, @1sn0s I'll check on my end. Meanwhile, you could also raise a PR with the update

**Comment by askmish** [comment]
I'm fully into poet 2.0 release work right now. So, there could be a delay in reporting back about the fix.

**Comment by askmish** [comment]
Has this issue been resolved?

**Comment by shonjs** [comment]
yes, this issue is resolved now.
