### ISSUE TITLE
Upgrade simplewallet to use Sawtooth 1.1

### ISSUE THREAD

**Issue by danintel** [askmish/sawtooth-simplewallet#39]
The changes are needed to the docker-compose .yaml files to use the `1.1` containers (instead of `1.0`) and to add a `devmode-engine-rust` container. 

The diffs should be very similar to the changes I made to cookiejar.  Here's the diffs:
https://github.com/danintel/sawtooth-cookiejar/commit/9f0b69ce104bd834289eca181df15b5ef3a5a6bd

The `sawtooth-validator` command line needs this new argument: `--bind consensus:tcp://eth0:5050`

The repository needs updating from 1.0 to "bumper" (1.1) and adding `[arch=amd64]` Something like:
`"deb [arch=amd64] http://repo.sawtooth.me/ubuntu/bumper/stable xenial universe"`

The dev-mode engine addition to the .yaml files should be something like:

```
+  devmode-engine:
+    image: hyperledger/sawtooth-devmode-engine-rust:1.1
+    ports:
+      - '5050:5050'
+    container_name: sawtooth-devmode-engine-rust-default
+    depends_on:
+      - validator
+    entrypoint: devmode-engine-rust --connect tcp://validator:5050
```

**Comment by askmish** [comment]
@danintel Good idea. I'm going to create a 1-1 branch in this repo right away. 
We'll merge the 1.1 branch to master when porting and testing is complete.
And then, move the entire current repo to 1-0 branch.

**Comment by sus536** [comment]
Hi , Could you also provide an update for Sawtooth 1.2? My project used to work with 1.0 and i recently updated to 1.2, but fails. It would be nice to have Dockerfiles to test the example again. Thanks

**Comment by danintel** [comment]
Try this version and let me know if it works:

https://github.com/danintel/sawtooth-simplewallet/tree/1-2


Here are the changes from Sawtooth 1.1:
https://github.com/askmish/sawtooth-simplewallet/compare/1-1...danintel:1-2?expand=1

Dan

**Comment by sus536** [comment]
Thanks i will check it out now.  
I actually decided to upgrade to Sawtooth 1.2 because of protobuf issues. I needed version>3, which is available in bionic as per this post https://github.com/hyperledger/education-sawtooth-simple-supply/pull/30
I am still relatively new with this. 
Does this update with Xenial universe solve that issue? Or does it have to be bionic as per the simple-supply example?
Thanks a lot!

**Comment by sus536** [comment]
Hi Dan,

Just wanted to update when i tried the new version as per this new commit.
I get this following error when attempting to install:

W: The repository 'http://repo.sawtooth.me/ubuntu/chime/stable xenial Release' does not have a Release file.
E: Failed to fetch http://repo.sawtooth.me/ubuntu/chime/stable/dists/xenial/universe/binary-amd64/Packages  404  Not Found [IP: 52.85.145.82 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.

Thanks!

**Comment by danintel** [comment]
Upgrading Ubuntu to Bionic and Sawtooth to 1.2+ solves the protobuf issues.

**Comment by danintel** [comment]
Try it again. I changed xenial to bionic

**Comment by sus536** [comment]
Hi Dan,

This is the new error i am getting.

Building simplewallet-client
Step 1/7 : FROM ubuntu:chime
ERROR: Service 'simplewallet-client' failed to build: manifest for ubuntu:chime not found: manifest unknown: manifest unknown

Thanks!

**Comment by danintel** [comment]
That should be ubuntu:bionic, not ubuntu:chime.
I fixed that, but there are some packages in xenial that do not exist in bionic.
Also the Sawtooth package names have changed.
I do not have time to fix this.

**Comment by sus536** [comment]
Hi Dan,

Thank you.
No problem, thanks for the lead. I will check the other examples and continue from here.

Thanks and Best Regards,

**Comment by sus536** [comment]
It works now! Thanks once again Dan.
Attaching the updated dockerfiles, if anyone needs it.
[sawtooth-1.2-dockerfiles.zip](https://github.com/askmish/sawtooth-simplewallet/files/4861459/sawtooth-1.2-dockerfiles.zip)

**Comment by danintel** [comment]
I added PR #49  to fix this
Please look at it and approve.
