### ISSUE TITLE
Error on building yaml file

### ISSUE THREAD

**Issue by rafaelkmelo** [askmish/sawtooth-simplewallet#51]
Some days ago the code was functioning well, but recently I get this error on compiling the simplewallet-build-tp.py file:

curl: (6) Could not resolve host: p80.pool.sks-keyservers.net
gpg: no valid OpenPGP data found.

The command '/bin/sh -c apt-get update  && apt-get install -y -q curl gnupg  && curl -sSL 'http://p80.pool.sks-keyservers.net/pks/lookup?op=get&search=0x8AA7AF1F1091A5FD' | apt-key add -   && echo 'deb [arch=amd64] http://repo.sawtooth.me/ubuntu/chime/stable bionic universe' >> /etc/apt/sources.list  && apt-get update' returned a non-zero code: 2
ERROR: Service 'simplewallet-client' failed to build : Build failed

**Comment by askmish** [comment]
@rafaelkmelo The issue seen could be due to http://p80.pool.sks-keyservers.net server. Please replace the 'http://p80.pool.sks-keyservers.net' with another PGP server like 'http://keyserver.ubuntu.com' or 'http://pgp.mit.edu' and try.

**Comment by rafaelkmelo** [comment]
That solved the problem. Thank you.
